#!/bin/bash

history -r ~/.dockerconsole_history

echo "Type help for available commands and quit to exit the console"

while [ $? -eq 0 ]; do

	if [ "$line" == "quit" ]; then
		exit
	fi
	
	if [ "$line" != "" ]; then
		history -s "$line"
		docker $line
	fi
	
	echo
	read -p "docker> " -r -e line
done

history -w ~/.dockerconsole_history
echo

